### ISSUE TITLE
failed to login: 503, Unknown data: b'103'

### ISSUE THREAD

**Issue by AshtonCampbell** [postlund/pyatv#121]
(My apologies if this is not the correct repo to post to, I wasn't sure whether to post this on the HA repo or here so I chose here.)

I'm running Home Assistant 0.54 and I'm consistently receiving this error when my Apple TV seems to be asleep. I usually have to restart my Apple TV and home assistant while playing something on my Apple TV before restarting HA to show the proper state of my Apple TV. After doing so it works well, but when it goes idle for a while this error will start to occur. I have a Apple TV 4K running the latest tvOS.

Errors I'm receiving: 

> 2017-10-05 01:19:00 WARNING (MainThread) [homeassistant.components.media_player.apple_tv] A <class 'pyatv.exceptions.AuthenticationError'> error occurred: failed to login: 503
> 2017-10-05 01:19:10 WARNING (MainThread) [pyatv.tag_definitions] Unknown data: b'103'
> 2017-10-05 01:19:10 WARNING (MainThread) [pyatv.tag_definitions] Unknown data: b'103'

**Comment by postlund** [comment]
It’s fine to handle it here! 😊

IIRC this usually usually happens when the login_id is not correct. But since it works for a while, that is probably not the case here. I think I need to work a bit on logging so that it’s easier to get better log data, because it’s hard to draw any conclusions from this I’m afraid. But you mention idle state and there is a big regarding that, see #115. Maybe it’s an issue because of that that is solved by my PR?

**Comment by AshtonCampbell** [comment]
Great!

> IIRC this usually usually happens when the login_id is not correct. But since it works for a while, that is probably not the case here.

I went ahead and made sure that my login_id was correct and it was, so I would also believe that is not the case.

>  But you mention idle state and there is a big regarding that, see #115. Maybe it’s an issue because of that that is solved by my PR?

That's good news! Once HA releases the new update on Saturday I will go ahead and get back to you if I'm still receiving this issue.

Just to note, I have an Apple TV 4K running on tvOS 11 and another Apple TV 4K running on tvOS 11.1 beta. The post above refers to the one running on tvOS 11. I will go ahead and test on both Apple TV's and get back to you with what I find. If you need anything from me to help troubleshoot just let me know!

**Comment by postlund** [comment]
Yeah, it seemed strange that it would work at all otherwise. But it's also strange that it responds with 503. Tried it at home just for the sake of if and specified an invalid login_id (using ``atvremote`` in this case) and it yielded the same error.

Perfect! I just bought an Apple TV 4K yesterday but I haven't added it to Home Assistant yet. I will wait for next release as well. Having a newer device will simplify debugging a lot and I hope that when I get MRP in place, that will remove a lot of issues as well. But it's not near future.

**Comment by AshtonCampbell** [comment]
I was fiddling around and considering that it may be something with my network that was causing this issue and funny enough I accidentally left my home assistant IP address port forwarding 8123 to 8123. This is from setting up letsencrypt. It seems that I am no longer having issues now in terms of getting the 503 error! Only issues now are due to the idle state which as you said has been fixed. :)

**Comment by postlund** [comment]
👍
