### ISSUE TITLE
Support for metadata via AirPlay 2

### ISSUE THREAD

**Issue by postlund** [postlund/pyatv#1255]
**Short feature/function description**
I have figured out that AirPlay 2 supports metadata via a special "remote control" channel, not something available in AirPlay 1. As I don't know how that channel works yet, I can't give any details but I'm working on it. As pyatv has no support for AirPlay 2, I have to start with that as well as add support in `atvproxy` (#1252) so I can see what's going on. Quite a big task, but I'm on my way...

**What needs to be done?**
One of the biggest thing with AirPlay 2 is that is requires "HAP based authentication", like MRP and Companion. It's almost exactly the same but carried over HTTP. I have prototyped that in the past and got something working, so I know what to do. It's just a big task to implement everything properly. Something I'm almost done with...

So far everything should be done on the "sender side", i.e. pyatv can perform pairing and set up an encrypted channel to an AirPlay 2 receiver and exchange messages over that channel. I have tested this with the "airplay" part, e.g. `play_url` and it works fine. I have however not adjusted RAOP to take advantage of this yet. I will take care of that soon enough but it's a bit tricker as all channels are encrypted (timing, control and audio), so it requires more work.

I have some refactoring to do, but I'm close to write the remaining parts in `atvproxy` as well. Finished paring on the sender side a while back so that a sender can pair (using transient pairing) with the proxy and set up encryption. Remaining part is to set up a connection to the receiver and relay messages back and forth. Shouldn't be that hard I hope.

Testing currently suffer a lot and I will have to put some effort into catching up later. But I'm trying to be pragmatic here, getting metadata to work again as pyatv will lose a lot of it's functionality when tvOS 15 is released. So I'm prioritizing feature support over testing right now.

**Is this a breaking change?**
No

**Anything else worth knowing?**
Currently, when pairing AirPlay with a device supporting HAP, HAP credentials will be returned. These will work fine for AirPlay, but won't work with RAOP as HAP based authentication is not supported by RAOP yet. Until I fix that, credentials for RAOP but be obtained from an earlier version of pyatv (unless I fix that before pushing my code).

**Comment by postlund** [comment]
So... wow, pretty excited right now. By doing more hacks than I can count, slashing my way through the code with a machete, I've managed to come up with a proxy that is good enough for my purposes. **I can see the AirPlay traffic between control center in iOS and my Apple TV in clear text!**

Guess what? MRP has moved in on its own channel! An example:

```
[setStateMessage] {
  playbackQueue {
    location: 0
    contentItems {
      identifier: "spotify:track:6tfPsgvkgbGHWGwq2PpzCI"
      metadata {
        title: "Goodbye"
        albumName: "Inside (The Songs)"
        trackArtistName: "Bo Burnham"
        duration: 249.428
        isExplicitItem: true
        artworkAvailable: true
        collectionIdentifier: "spotify:playlist:37i9dQZF1EIY1iI5V6fdka"
        artworkMIMEType: "image/jpeg"
        discNumber: 2
        elapsedTime: 0.033716898918151855
        playbackRate: 1.0
        totalDiscCount: 2
        totalTrackCount: 20
        trackNumber: 8
        contentIdentifier: "spotify:track:6tfPsgvkgbGHWGwq2PpzCI"
        mediaType: Audio
        mediaSubType: Music
        nowPlayingInfoData: "bplist00\324\001\002\003\004\005\006\007\nX$versionY$archiverT$topX$objects\022\000\001\206\240_\020\017NSKeyedArchiver\321\010\tTroot\200\001\246\013\014\027\030\031\032U$null\323\r\016\017\020\023\026WNS.keysZNS.objectsV$class\242\021\022\200\002\200\003\242\024\024\200\004\200\004\200\005_\020,kMRMediaRemoteNowPlayingInfoArtworkDataWidth_\020-kMRMediaRemoteNowPlayingInfoArtworkDataHeight\021\002X\322\033\034\035\036Z$classnameX$classes\\NSDictionary\242\035\037XNSObject\000\010\000\021\000\032\000$\000)\0002\0007\000I\000L\000Q\000S\000Z\000`\000g\000o\000z\000\201\000\204\000\206\000\210\000\213\000\215\000\217\000\221\000\300\000\360\000\363\000\370\001\003\001\014\001\031\001\034\000\000\000\000\000\000\002\001\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\000\000\000\000\000\000\000\001%"
        elapsedTimeTimestamp: 651097077.389096
        artworkIdentifier: "913D9EFE-FC43-44C8-BA1D-0153FD110C30"
        legacyUniqueIdentifier: 5855976077825122148
      }
    }
  }
  playbackQueueCapabilities {
  }
  playerPath {
    origin {
      displayName: "Vardagsrum"
      identifier: 1280262988
    }
    client {
      processIdentifier: 137
      bundleIdentifier: "com.apple.TVAirPlay"
    }
    player {
      identifier: "MediaRemote-DefaultPlayer"
      displayName: "Default Player"
    }
  }
}
uniqueIdentifier: "133C7954-E9D6-44F6-82EE-7272AD7CE462"
```
I have only listened to incoming data on that channel, not tried to send anything. But it might work to send commands upstream as well.

This is really good news as it means there's a way forward after MRP (as we currently know it) is removed. There's however a *lot* of work to make whatever I have working. There's also a lot of things I have not looked into or figured out yet (sent on the various channels). I need to prototype a client implementation not relying on the proxy and start documenting so I know what I'm doing. And to give others the chance to follow. I'm also not sure how to implement this in the best way. Maybe I can create some kind of abstraction so I can re-use all code from MRP that I already have? Need to think about that and maybe prototype it a bit.

I'm gonna disclose as much as I can when possible. From what I've gathered, this has not been reversed before (at least publicly) so it's important to document properly.

Now, I deserve some sleep after the countless amount of hours put into this 🎉 😴

**Comment by postlund** [comment]
I've summarized and published documentation for the protocol that's good enough to get going. Next step is to continue to implement parts of this. I need to sit down and look at my proxy to come up with tasks to do. Will start with that tonight. I'm hoping to have a working prototype for testing by the end of next week or so. Let's hope I can get there!

**Comment by postlund** [comment]
I'm gonna need some beta testers for this soon-ish. If you have an Apple TV (preferably running tvOS 15, but earlier works too), knowledge to run pyatv from a PR and some time it would be highly appreciated if you can help me. It will be early work, basically just verifying that setting up a connection works. Nothing more fancy than that. Also, only Apple TV for now. Will make HomePod work at a later stage. Might also need some help verifying if this interface is available for third party receivers as well (I doubt it is though as MRP is an internal protocol).

**Comment by mattsch** [comment]
I can help test, but still on tvOS 14 for the time being.

**Comment by BVGorp** [comment]
I can test too. Apple TV 4k tvOS 15 latest beta.

**Comment by postlund** [comment]
That's great, thank you! I will try to come up with something testable by tonight I hope. Otherwise by tomorrow.

**Comment by postlund** [comment]
I will redact my previous statement and take another day or two to clean things up a bit. Kinda got carried away and started prototyping a connection wrapper for the MRP protocol. This allowed me to setup a connection via AirPlay and setup MRP on top of that, thus re-using my entire MRP implementation. Guess what? It worked! It's just a big hack and some things aren't working, but it's a really good start. I can issue for instance `playing` and get what is playing or send remote control commands. Pretty cool! 😎

**Comment by postlund** [comment]
@mattsch @BVGorp PR #1263 ready for testing!

**Comment by mscodemonkey** [comment]
Will gladly help with testing in any way I can too!

**Comment by postlund** [comment]
@mscodemonkey Thats great! Everything you need is in: https://github.com/postlund/pyatv/pull/1263

**Comment by BVGorp** [comment]
Hi tried compiing again but next error:

```
Best match: miniaudio 1.44
Processing miniaudio-1.44.tar.gz
Writing /tmp/easy_install-xxzu3_nn/miniaudio-1.44/setup.cfg
Running miniaudio-1.44/setup.py -q bdist_egg --dist-dir /tmp/easy_install-xxzu3_nn/miniaudio-1.44/egg-dist-tmp-heyze4px
no previously-included directories found matching 'examples'
build/temp.linux-x86_64-3.8/_miniaudio.c:50:14: fatal error: pyconfig.h: No such file or directory
 #    include <pyconfig.h>
              ^~~~~~~~~~~~
compilation terminated.
```

updated to python 3.8 now same error

**Comment by postlund** [comment]
@BVGorp Not sure which distro you are running, but assuming a Debian based one, this should solve it:

    sudo apt-get install python3-dev

**Comment by BVGorp** [comment]
Running Ubuntu bionic. Did the command, and it gets further in the process, but still errors :(
You on Discord by any chance?

```
Running cryptography-3.4.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lq5u7d2u/cryptography-3.4.8/egg-dist-tmp-1vdxsmq_

        =============================DEBUG ASSISTANCE==========================
        If you are seeing an error here please try the following to
        successfully install cryptography:

        Upgrade to the latest pip and try again. This will fix errors for most
        users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        =============================DEBUG ASSISTANCE==========================
        
Traceback (most recent call last):
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-lq5u7d2u/cryptography-3.4.8/setup.py", line 14, in <module>
    
ModuleNotFoundError: No module named 'setuptools_rust'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    setup(
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/develop.py", line 152, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 770, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    dist = best[req.key] = env.best_match(
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/opt/pyatv_pr/pyatv/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-lq5u7d2u/cryptography-3.4.8/setup.py", line 14, in <module>
    
ModuleNotFoundError: No module named 'setuptools_rust'
```

**Comment by postlund** [comment]
Finished and done!

**Comment by Ajay-ue** [comment]
I pip installed pyatv on my ubuntu linux 18.04 machine. I upgraded my apple TV to use TVOS-15 beta. I am able to pair thru companion link but still not thru mrp (or airplay). 
ATVRemote shows version 0.9.1 so I guess it should have worked as you fixed the issue of MRP not functioning on 0.9.0. Could you please let me know whats wrong here.
When I use airplay protocol for pairing it never shows pin on TV screen. While MRP simply throws error.

**Comment by postlund** [comment]
It is not possible to pair MRP as that has been removed, but AirPlay should work. What is the output of `atvremote scan`?

**Comment by Ajay-ue** [comment]
Following is the scan response -
Scan Results
========================================
       Name: Apple TV (16367)
   Model/SW: Gen4 tvOS 15.0 build 19J346
    Address: 192.168.0.105
        MAC: D0:03:4B:2B:A6:8F
 Deep Sleep: True
Identifiers:
 - D0:03:4B:2B:A6:8F
 - 3A5AD3D3-6C1B-4651-A19D-282C0346AB6E
 - D0034B2BA68F
Services:
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password:
True, Password: None, Pairing: Mandatory
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password:
False, Password: None, Pairing: Mandatory
 - Protocol: MRP, Port: 49152, Credentials: None, Requires Password: False,
Password: None, Pairing: Optional
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: True,
Password: None, Pairing: NotNeeded
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

But when I try to pair with => atvremote --id <xyz> --protocol airplay
pair  => It does not pop a pin on screen... while atvremote is asking for
pin displayed in TV.

Thanks & Regards
Aj

**Comment by postlund** [comment]
You have password enabled and pyatv does not support that for AirPlay yet.

**Comment by Ajay-ue** [comment]
Hi Pierre,

Thanks for the quick reply. Disabling the password also did not work for
me. Yes, this time apple tv displays the pin on TV but after entering the
pin it throws a series of exceptions. Please see attached error log.
BTW, Pairing with 'companion' is working fine... but commands are not
working. When I tried to pass the 'right' key command, it throws an error
saying pair with airplay first (something like that) and a pin is displayed
on the TV screen automatically.
Thanks & Regards,
Ajay

**Comment by postlund** [comment]
I think you managed to miss the error log, no?

How are you calling the commands? I don't see how that could trigger a message about pairing in any way. You should use the `remote.send_command` service for that.

**Comment by postlund** [comment]
Hmm, it probably doesn't work when responding by mail. Either paste the log here or preferably send it by email to me directly.

**Comment by Ajay-ue** [comment]
Okay ---------------- pasted it below -


***@***.***:~$ atvremote scan
Scan Results
========================================
       Name: Apple TV (16367)
   Model/SW: Gen4 tvOS 15.0 build 19J346
    Address: 192.168.0.105
        MAC: D0:03:4B:2B:A6:8F
 Deep Sleep: True
Identifiers:
 - D0:03:4B:2B:A6:8F
 - 3A5AD3D3-6C1B-4651-A19D-282C0346AB6E
 - D0034B2BA68F
Services:
 - Protocol: Companion, Port: 49153, Credentials: None, Requires Password:
False, Password: None, Pairing: Mandatory
 - Protocol: AirPlay, Port: 7000, Credentials: None, Requires Password:
False, Password: None, Pairing: Mandatory
 - Protocol: MRP, Port: 49152, Credentials: None, Requires Password: False,
Password: None, Pairing: Optional
 - Protocol: RAOP, Port: 7000, Credentials: None, Requires Password: False,
Password: None, Pairing: Mandatory

***@***.***:~$ atvremote --id D0:03:4B:2B:A6:8F --protocol
airplay pair
Enter PIN on screen: 1978
2021-09-30 10:52:47 ERROR [pyatv.scripts.atvremote]: Pairing failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/support/http.py", line
388, in send_and_receive
    await asyncio.wait_for(event.wait(), timeout=4)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/support/__init__.py",
line 33, in error_handler
    return await func(*args, **kwargs)
  File
"/usr/local/lib/python3.6/dist-packages/pyatv/protocols/airplay/auth/hap.py",
line 78, in finish_pairing
    "/pair-setup", body=hap_tlv8.write_tlv(data), headers=_AIRPLAY_HEADERS
  File "/usr/local/lib/python3.6/dist-packages/pyatv/support/http.py", line
360, in post
    "POST", path, headers=headers, body=body, allow_error=allow_error
  File "/usr/local/lib/python3.6/dist-packages/pyatv/support/http.py", line
391, in send_and_receive
    raise TimeoutError(f"no response to {method} {uri} ({protocol})") from
ex
TimeoutError: no response to POST /pair-setup (HTTP/1.1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyatv/scripts/atvremote.py",
line 172, in pair
    await self._perform_pairing(pairing)
  File "/usr/local/lib/python3.6/dist-packages/pyatv/scripts/atvremote.py",
line 205, in _perform_pairing
    await pairing.finish()
  File
"/usr/local/lib/python3.6/dist-packages/pyatv/protocols/airplay/pairing.py",
line 78, in finish
    self.pin_code,
  File "/usr/local/lib/python3.6/dist-packages/pyatv/support/__init__.py",
line 35, in error_handler
    raise exceptions.ConnectionFailedError(str(ex)) from ex
pyatv.exceptions.ConnectionFailedError: no response to POST /pair-setup
(HTTP/1.1)
***@***.***:~$

**Comment by Ajay-ue** [comment]
Also - I am using following command on linux terminal using companion
credentials - ( i thought it should work :))
atvremote --id D0:03:4B:2B:A6:8F --companion-credentials
67962644eb5c1426be5f6661e10385f416ec4833137e5acfc5380074ae3eecad:6ca12af62eac6ce57a137ea0a1ca042748ccc998ea423047a5002d519cbc061d:44383046333643332d313944302d344446372d424241352d324537374132343033393737:36336264613235632d316534332d346231662d393735302d636333616436373435383439
right

**Comment by postlund** [comment]
That looks correct to me, so maybe a bug. Can you add `--debug` when pairing, maybe that gives a clue?

The command for sending `right` also looks good, what was the output?

**Comment by Ajay-ue** [comment]
Logs Sent to your gmail account.

**Comment by postlund** [comment]
Ok, I understand the `right` issue now. It's basically because pyatv discovers the MRP protocols and tries to connect to it, but since it's broken in tvOS 15 that doesn't work. I think I will try to make a check and ignore that protocol for tvOS 15 devices. Let's see if I can solve that by tomorrow or so.

You can work around that by not scanning for that protocol, e.g. like this (you need one other protocol in conjunction with Companion):

    atvrremote --id <id> --scan-protocols companion,raop --companion-credentials <creds> right

**Comment by postlund** [comment]
I opened #1357 to deal with MRP.

**Comment by Ajay-ue** [comment]
Thanks Pierre,

I tried the workaround you suggested but that did not work for me - here is
the output with debug -
***@***.***:~$ atvremote --debug --id D0:03:4B:2B:A6:8F
--scan-protocols companion,raop --companion-credentials
67962644eb5c1426be5f6661e10385f416ec4833137e5acfc5380074ae3eecad:21c3dfdef0bc94964d1237f941a72b0a58178568c18b05c9e93d19c8ac33591a:44383046333643332d313944302d344446372d424241352d324537374132343033393737:65333631646163392d346131372d343732372d386338342d386136626535653537373239
right
2021-09-30 15:18:32 DEBUG [pyatv.support.net]: Binding on *:5353
2021-09-30 15:18:32 DEBUG [pyatv.support.net]: Binding on 127.0.0.1:0
2021-09-30 15:18:32 DEBUG [pyatv.support.net]: Binding on 192.168.0.107:0
2021-09-30 15:18:32 DEBUG [pyatv.support.net]: Binding on 192.168.250.1:0
2021-09-30 15:18:35 DEBUG [pyatv.core.scan]: Auto-discovered Apple TV
(16367) at 192.168.0.105:49152 via Protocol.Companion ({'rpmac': '1',
'rphn': '88761ab2dbaf', 'rpfl': '0x36782', 'rpmd': 'AppleTV5,3', 'rpvr':
'300.66', 'rpmrtid': 'D80F36C3-19D0-4DF7-BBA5-2E77A2403977', 'rpad':
'03cdb6821465', 'rpba': 'EF:88:23:61:9A:91'})
2021-09-30 15:18:35 DEBUG [pyatv.core.scan]: Auto-discovered
***@***.*** TV (16367) at 192.168.0.105:7000 via Protocol.RAOP
({'cn': '0,1,2,3', 'da': 'true', 'et': '0,3,5', 'ft':
'0x5A7FDFD5,0xBC155FDE', 'sf': '0x10244', 'md': '0,1,2', 'am':
'AppleTV5,3', 'pk':
'7c6ddfe1df237bd931d037f5855f035280cc1ea8c211ba49df041d9455ad6fb6', 'tp':
'UDP', 'vn': '65537', 'vs': '566.25.43', 'ov': '15.0', 'vv': '2'})
2021-09-30 15:18:35 ERROR [pyatv.scripts.atvremote]: Could not find any
Apple TV on current network

**Comment by postlund** [comment]
Ok, the value you pass comes from one of the other services that you are no longer scanning for. Do this:

    atvremote --scan-protocols raop,companion scan

Then pick one of the identifiers there instead (should only be one) and pass that to `--id`.

**Comment by Ajay-ue** [comment]
Hi Pierre,

I did that but it seems not to be working. Although I did not receive any
error, it had no effect on screen. For example 'right' key should make a
shift to right from TV icon to Movies... but nothing happens.  Scanning and
pairing happens fine. Just in case if you want to see, I have attached the
log.

**Comment by postlund** [comment]
It looks ok to me in the log. But honestly... I have not tested all of the buttons 😅 I suspect the navigational buttons doesn't work in the same way as power on for instance, which I used as a base. I have a theory of how it should work, I can prepare a PR if you want to help out testing it?

**Comment by postlund** [comment]
It would be really great if you could try the various supported buttons and open a bug issue here, it's very easy that I miss or forget things otherwise.

**Comment by Ajay-ue** [comment]
sure I can help you with that.
Regards
Aj

**Comment by postlund** [comment]
I made a small change and uploaded this branch:

https://github.com/postlund/pyatv/tree/companion_rc_presses

Maybe that works?

**Comment by Ajay-ue** [comment]
Hi Pierre,

I tested this and navigation keys working with companion link. I'll check
further other commands. Which do you think is better to use for a remote
control key ? airplay or companion ? Also airplay/mrp fix release date ?

Regards
Aj

**Comment by Ajay-ue** [comment]
I meant that I tested it to pair with airplay and that still doesn't work -
regards, Aj

**Comment by postlund** [comment]
@Ajay-ue You can only see what app is currently playing something, not which app is currently open on screen.
