### ISSUE TITLE
API Timeout HASS Remote

### ISSUE THREAD

**Issue by fenderle** [postlund/pyatv#726]
**Describe the bug**
When I disconnect and reconnect the AppleTV's network cable the following commands send by the HomeAssistant integration timeout until I restart  HomeAssistant.

**To Reproduce**
- Configure a static IP or assure DHCP issues the same IP address to the ATV
- Verifiy integration works
- Pull network cable from ATV
- Connect network cable to ATV
- Commands from HomeAssistant to the ATV will now time out

**Expected behavior**
Command times out and connection is reestablished and command is retried.

**System Setup (please complete the following information):**
 - OS: HomeAssistant Docker container
 - Python: The version which comes in the container
 - pyatv: 0.6.1U3 (the repo with power management support)
- Apple TV: Apple TV 4 tvOS 13.4.6

**Additional context**
A remote command which I could send using remote.send_command to reconnect the ATV would be sufficient. I just don't want always to restart HomeAssistant. As for 'Why would you reconnect the network' - I have situations where I have to clear all network information caches (DNS) on the AppleTV and the easiest way to do this from NodeRED is to disable/enable the switch port where the ATV is connected to.

**Comment by postlund** [comment]
The same issue was brought to my intention almost a week ago in #708 and I have merged a fix for it and will be ready once I get 0.7.0 out the doors. Please see mentioned issue for details.

**Comment by fenderle** [comment]
Perfect!

**Comment by postlund** [comment]
Just pushed an update to the component, can you try it out and see if it works?

**Comment by fenderle** [comment]
Sorry for the delay... Must have missed the notification...

Still doesn't work. I changed to the last release and verified the 0.7.0 version has been installed in the container. Even after several minutes it doesn't work:

```
Jul 25 22:18:47 streambox docker[684722]: 2020-07-25 22:18:47 ERROR (MainThread) [homeassistant.components.tp.connection.139929417516416]
Jul 25 22:18:47 streambox docker[684722]: Traceback (most recent call last):
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
Jul 25 22:18:47 streambox docker[684722]:     await hass.services.async_call(
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/core.py", line 1265, in async_call
Jul 25 22:18:47 streambox docker[684722]:     task.result()
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/core.py", line 1300, in _execute_service
Jul 25 22:18:47 streambox docker[684722]:     await handler.func(service_call)
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
Jul 25 22:18:47 streambox docker[684722]:     await self.hass.helpers.service.entity_service_call(
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
Jul 25 22:18:47 streambox docker[684722]:     future.result()  # pop exception if have
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
Jul 25 22:18:47 streambox docker[684722]:     await coro
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
Jul 25 22:18:47 streambox docker[684722]:     await result
Jul 25 22:18:47 streambox docker[684722]:   File "/config/custom_components/apple_tv/media_player.py", line 269, in async_media_play_pause
Jul 25 22:18:47 streambox docker[684722]:     await self.atv.remote_control.pause()
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 212, in pause
Jul 25 22:18:47 streambox docker[684722]:     await self._send_command(CommandInfo_pb2.Pause)
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/__init__.py", line 164, in _send_command
Jul 25 22:18:47 streambox docker[684722]:     resp = await self.protocol.send_and_receive(messages.command(command, **kwargs))
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 138, in send_and_receive
Jul 25 22:18:47 streambox docker[684722]:     return await self._receive(identifier, timeout)
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/local/lib/python3.8/site-packages/pyatv/mrp/protocol.py", line 146, in _receive
Jul 25 22:18:47 streambox docker[684722]:     await asyncio.wait_for(semaphore.acquire(), timeout)
Jul 25 22:18:47 streambox docker[684722]:   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
Jul 25 22:18:47 streambox docker[684722]:     raise exceptions.TimeoutError()
Jul 25 22:18:47 streambox docker[684722]: asyncio.exceptions.TimeoutError
```

**Comment by postlund** [comment]
Ok, that is interesting (and sorry about the delay, took some vacation). Can you try running with atvremote instead, e.g. `atvremote --debug -s <ip> push_updates`, then pull the cable and see what happens? The logs would be useful.

**Comment by fenderle** [comment]
So first of all sorry for not responding for a while. I was really distracted the last few months. Meanwhile I switched to an ATV4k, so just a disclaimer that this might introduce differences.

With the current configuration it seems to work without errors and seems to be reliable (0.7.3). The push_updates command however stops working once you pull and reconnect the port:

```
Press ENTER to stop
  Media type: Unknown
Device state: Idle
      Repeat: Off
     Shuffle: Off
--------------------
2020-10-27 08:54:38 DEBUG: 192.168.x.110:56700<->192.168.x.102:49153 Disconnected from device: [Errno 110] Operation timed out
Connection lost with error: [Errno 110] Operation timed out
```

And it does not 'revive' itself.

**Comment by postlund** [comment]
That's intended behavior as no re-connect logic is in place, will close issue now. Thanks for testing!
